name: Publish
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  publish_packages:
    name: Publish Packages
    uses: yaml-js/.github/.github/workflows/jobs.publish.yml@main
    permissions:
      contents: write
    with:
      KEY: ${{ github.sha }}
      REF_NAME: ${{ github.ref_name }}
